#!/usr/bin/env bash
# ==================================================
# lib/drift/autofix.sh — Drift auto-fix configuration
# ==================================================
# Requires: lib/utils.sh sourced first
#
# Manages auto-fix configuration for drift detection

# Source utils if not already sourced
set -euo pipefail

if [ -z "$RED" ]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  source "$SCRIPT_DIR/utils.sh"
fi

# drift_autofix_enable <stack> <env>
# Enables auto-fix for a stack
drift_autofix_enable() {
  local stack="$1"
  local env="${2:-prod}"

  local cli_root="${CLI_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
  local stack_dir="$cli_root/stacks/$stack"
  local config_file="$stack_dir/drift.conf"

  [ -d "$stack_dir" ] || {
    error "Stack directory not found: $stack_dir"
    return 1
  }

  log "Enabling drift auto-fix for $stack..."

  # Create or update config file
  if [ -f "$config_file" ]; then
    # Update existing config
    if grep -q "^DRIFT_AUTOFIX_ENABLED=" "$config_file"; then
      sed -i "s|^DRIFT_AUTOFIX_ENABLED=.*|DRIFT_AUTOFIX_ENABLED=true|" "$config_file"
    else
      echo "DRIFT_AUTOFIX_ENABLED=true" >>"$config_file"
    fi
  else
    # Create new config
    cat >"$config_file" <<EOF
# Drift detection configuration
# Auto-generated by strut

# Enable automatic drift fixing
DRIFT_AUTOFIX_ENABLED=true

# Environment for auto-fix
DRIFT_AUTOFIX_ENV=$env

# Run health checks after auto-fix
DRIFT_AUTOFIX_HEALTH_CHECK=true

# Rollback on health check failure
DRIFT_AUTOFIX_ROLLBACK_ON_FAILURE=true
EOF
  fi

  ok "Drift auto-fix enabled for $stack"

  # Update cron job to include auto-fix
  if [ -f "$cli_root/lib/drift/schedule.sh" ]; then
    source "$cli_root/lib/drift/schedule.sh"

    # Remove existing cron job
    drift_schedule_remove "$stack" >/dev/null 2>&1

    # Install new cron job with auto-fix
    local schedule="0 * * * *" # Hourly
    local cron_cmd="$schedule cd $cli_root && strut $stack drift monitor --env $env --auto-fix >> $cli_root/stacks/$stack/drift-history/monitor.log 2>&1"

    (
      crontab -l 2>/dev/null | grep -v "drift monitor.*$stack"
      echo "$cron_cmd"
    ) | crontab -

    ok "Cron job updated with auto-fix enabled"
  fi

  return 0
}

# drift_autofix_disable <stack>
# Disables auto-fix for a stack
drift_autofix_disable() {
  local stack="$1"

  local cli_root="${CLI_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
  local stack_dir="$cli_root/stacks/$stack"
  local config_file="$stack_dir/drift.conf"

  [ -d "$stack_dir" ] || {
    error "Stack directory not found: $stack_dir"
    return 1
  }

  log "Disabling drift auto-fix for $stack..."

  # Update config file
  if [ -f "$config_file" ]; then
    if grep -q "^DRIFT_AUTOFIX_ENABLED=" "$config_file"; then
      sed -i "s|^DRIFT_AUTOFIX_ENABLED=.*|DRIFT_AUTOFIX_ENABLED=false|" "$config_file"
    else
      echo "DRIFT_AUTOFIX_ENABLED=false" >>"$config_file"
    fi
  else
    # Create config with auto-fix disabled
    cat >"$config_file" <<EOF
# Drift detection configuration
DRIFT_AUTOFIX_ENABLED=false
EOF
  fi

  ok "Drift auto-fix disabled for $stack"

  # Update cron job to remove auto-fix
  if [ -f "$cli_root/lib/drift/schedule.sh" ]; then
    source "$cli_root/lib/drift/schedule.sh"

    # Remove existing cron job
    drift_schedule_remove "$stack" >/dev/null 2>&1

    # Install new cron job without auto-fix
    local env="${DRIFT_AUTOFIX_ENV:-prod}"
    local schedule="0 * * * *" # Hourly
    local cron_cmd="$schedule cd $cli_root && strut $stack drift monitor --env $env >> $cli_root/stacks/$stack/drift-history/monitor.log 2>&1"

    (
      crontab -l 2>/dev/null | grep -v "drift monitor.*$stack"
      echo "$cron_cmd"
    ) | crontab -

    ok "Cron job updated with auto-fix disabled"
  fi

  return 0
}

# drift_autofix_status <stack>
# Shows auto-fix status for a stack
drift_autofix_status() {
  local stack="$1"

  local cli_root="${CLI_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
  local stack_dir="$cli_root/stacks/$stack"
  local config_file="$stack_dir/drift.conf"

  [ -d "$stack_dir" ] || {
    error "Stack directory not found: $stack_dir"
    return 1
  }

  echo -e "${BLUE}=================================================="
  echo -e "  Drift Auto-Fix Status: $stack"
  echo -e "==================================================${NC}"
  echo ""

  if [ ! -f "$config_file" ]; then
    log "Auto-fix: disabled (no configuration file)"
    return 0
  fi

  # Read config
  local autofix_enabled="false"
  local autofix_env="prod"
  local health_check="true"
  local rollback_on_failure="true"

  if [ -f "$config_file" ]; then
    source "$config_file"
    autofix_enabled="${DRIFT_AUTOFIX_ENABLED:-false}"
    autofix_env="${DRIFT_AUTOFIX_ENV:-prod}"
    health_check="${DRIFT_AUTOFIX_HEALTH_CHECK:-true}"
    rollback_on_failure="${DRIFT_AUTOFIX_ROLLBACK_ON_FAILURE:-true}"
  fi

  echo "Auto-fix enabled: $autofix_enabled"
  echo "Environment: $autofix_env"
  echo "Health check after fix: $health_check"
  echo "Rollback on failure: $rollback_on_failure"
  echo ""

  # Check cron job
  if crontab -l 2>/dev/null | grep -q "drift monitor.*$stack.*--auto-fix"; then
    ok "Cron job configured with auto-fix"
  elif crontab -l 2>/dev/null | grep -q "drift monitor.*$stack"; then
    log "Cron job configured without auto-fix"
  else
    warn "No cron job configured"
  fi

  return 0
}

# drift_autofix_run <stack> <env>
# Runs auto-fix if enabled (called by drift_monitor)
drift_autofix_run() {
  local stack="$1"
  local env="${2:-prod}"

  local cli_root="${CLI_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
  local stack_dir="$cli_root/stacks/$stack"
  local config_file="$stack_dir/drift.conf"

  # Check if auto-fix is enabled
  local autofix_enabled="false"
  if [ -f "$config_file" ]; then
    source "$config_file"
    autofix_enabled="${DRIFT_AUTOFIX_ENABLED:-false}"
  fi

  if [ "$autofix_enabled" != "true" ]; then
    return 1 # Auto-fix not enabled
  fi

  # Source drift.sh for drift_fix function
  source "$cli_root/lib/drift.sh"

  # Run drift fix
  log "Auto-fix enabled, applying git-tracked configuration..."
  if drift_fix "$stack" "$env"; then
    ok "Auto-fix completed successfully"
    return 0
  else
    error "Auto-fix failed"
    return 1
  fi
}
