#!/usr/bin/env bash
# ==================================================
# lib/cmd_skills.sh — Install AI agent context for strut projects
# ==================================================
# Requires: lib/utils.sh sourced first
#
# Provides:
#   cmd_skills <subcommand>
#
# Two types of content:
#   Steering  — always-on context (conventions, architecture, config patterns)
#   Skills    — on-demand procedures (deploy, debug, backup, etc.)
#
# Supported tools:
#   kiro, claude, cursor, windsurf, zed, copilot, cline, agents, generic

set -euo pipefail

cmd_skills() {
  local subcmd="${1:-}"

  case "$subcmd" in
    install)  _skills_install "${@:2}" ;;
    list)     _skills_list ;;
    ""|help)  _skills_usage ;;
    *)        _skills_usage; fail "Unknown skills subcommand: $subcmd" ;;
  esac
}

_skills_install() {
  local format="kiro"

  while [[ $# -gt 0 ]]; do
    case $1 in
      --format=*) format="${1#*=}"; shift ;;
      --format)   format="$2"; shift 2 ;;
      -*)         fail "Unknown option: $1 (run 'strut skills help' for usage)" ;;
      *)          format="$1"; shift ;;  # positional arg = format
    esac
  done

  local strut_home="${STRUT_HOME:-$CLI_ROOT}"
  local skills_src="$strut_home/.kiro/skills"
  local steering_src="$strut_home/.kiro/steering"
  local project_root="${PROJECT_ROOT:-$PWD}"

  [ -d "$skills_src" ] || fail "Skills not found at $skills_src"

  case "$format" in
    kiro)     _install_kiro "$strut_home" "$project_root" ;;
    claude)   _install_claude "$strut_home" "$project_root" ;;
    cursor)   _install_rules_file "$strut_home" "$project_root" ".cursorrules" "Cursor" "cursor" ;;
    windsurf) _install_rules_file "$strut_home" "$project_root" ".windsurfrules" "Windsurf" "windsurf" ;;
    zed)      _install_rules_file "$strut_home" "$project_root" ".rules" "Zed" ;;
    cline)    _install_rules_file "$strut_home" "$project_root" ".clinerules" "Cline" ;;
    copilot)  _install_copilot "$strut_home" "$project_root" ;;
    agents)   _install_rules_file "$strut_home" "$project_root" "AGENTS.md" "AGENTS.md-compatible tools" ;;
    generic)  _install_generic "$strut_home" "$project_root" ;;
    all)      _install_all "$strut_home" "$project_root" ;;
    *)        fail "Unknown format: $format (run 'strut skills help' for supported formats)" ;;
  esac
}

# ── Helpers: build steering and skills content ────────────────────────────────

# Build the steering block (conventions, architecture, always-on context)
_build_steering_content() {
  local strut_home="$1"
  local steering_dir="$strut_home/.kiro/steering"
  local claude_md="$strut_home/CLAUDE.md"

  # Tag so we know this was generated (can safely overwrite on next install)
  echo "<!-- strut:skills-generated -->"
  echo ""

  # Start with CLAUDE.md if it exists (it's the canonical developer context)
  if [ -f "$claude_md" ]; then
    cat "$claude_md"
  else
    echo "# strut — VPS Stack Management CLI"
    echo ""
    echo "Bash CLI tool for managing Docker stacks on VPS infrastructure."
  fi

  # Append steering files
  if [ -d "$steering_dir" ]; then
    for steering_file in "$steering_dir"/*.md; do
      [ -f "$steering_file" ] || continue
      echo ""
      echo "---"
      echo ""
      # Strip YAML frontmatter
      awk 'BEGIN{fm=0} /^---$/{fm++; next} fm>=2||fm==0{print}' "$steering_file"
    done
  fi
}

# Build the skills block (on-demand procedures)
#
# Flat rules files (Cursor, Copilot, AGENTS.md, etc.) have no progressive
# disclosure, so we inline the skill's SKILL.md body plus every reference file.
_build_skills_content() {
  local strut_home="$1"
  local skills_dir="$strut_home/.kiro/skills"

  echo "## Operational Procedures"
  echo ""
  echo "Reference procedures for common strut operations."

  for skill_dir in "$skills_dir"/*/; do
    [ -d "$skill_dir" ] || continue
    local skill_file="$skill_dir/SKILL.md"
    [ -f "$skill_file" ] || continue

    echo ""
    echo "---"
    echo ""
    # Strip YAML frontmatter from the router body
    awk 'BEGIN{fm=0} /^---$/{fm++; next} fm>=2||fm==0{print}' "$skill_file"

    # Inline every reference file (flat formats can't load them on demand)
    if [ -d "$skill_dir/references" ]; then
      local ref
      for ref in "$skill_dir/references"/*.md; do
        [ -f "$ref" ] || continue
        echo ""
        echo "---"
        echo ""
        cat "$ref"
      done
    fi
  done
}

# _backup_if_exists <file_path> <label>
#
# If the file exists and was NOT previously generated by strut skills,
# creates a timestamped backup and warns the user.
_backup_if_exists() {
  local file_path="$1"
  local label="$2"

  [ -f "$file_path" ] || return 0

  # Check if it's a strut-generated file (we tag them)
  if grep -q "^<!-- strut:skills-generated -->" "$file_path" 2>/dev/null; then
    return 0  # Safe to overwrite our own generated files
  fi

  local backup="${file_path}.backup-$(date +%Y%m%d-%H%M%S)"
  cp "$file_path" "$backup"
  warn "Backed up existing $label → $(basename "$backup")"
}

# ── agent-add: multi-editor skill installer ───────────────────────────────────
# agent-add (https://github.com/pea3nut/agent-add) natively understands the
# Agent Skills directory spec (a SKILL.md-rooted folder) and knows the right
# skills location per editor. Only a subset of strut's formats map to a real
# agent-add host — zed and cline aren't in its host list — so this is used
# where available and every caller falls back to strut's own directory copy
# when it isn't (no npx, no network, or the call itself fails).

# _agent_add_install_skills <strut_home> <host_id> <label>
#
# Installs every strut skill directory (anything under .kiro/skills/ with a
# SKILL.md) to the given agent-add host in one invocation. Echoes the number
# of skills installed and returns 0 on success; returns 1 (no output on
# stdout) if npx can't be resolved, there are no skills to install, or
# agent-add itself fails — callers should fall back to their own install
# path in that case.
#
# Callers capture this via `skill_count=$(... _agent_add_install_skills ...)`,
# so every log/warn call here must go to stderr explicitly — log()/warn()
# both write to stdout by default, and command substitution captures ALL of
# a subshell's stdout, not just the final echo. Left as plain stdout calls,
# the progress message corrupts the captured count on success, and the
# fallback warning is silently swallowed (never reaches the user) on failure.
_agent_add_install_skills() {
  local strut_home="$1"
  local host_id="$2"
  local label="$3"

  local npx_bin=""
  resolve_npx_bin && npx_bin="$RESOLVED_NPX_BIN" || return 1

  local -a skill_args=()
  local skill_dir
  for skill_dir in "$strut_home/.kiro/skills"/*/; do
    [ -f "$skill_dir/SKILL.md" ] || continue
    skill_args+=(--skill "$skill_dir")
  done
  [ "${#skill_args[@]}" -gt 0 ] || return 1

  log "$label: installing $(( ${#skill_args[@]} / 2 )) skill(s) via agent-add..." >&2
  if ! "$npx_bin" -y agent-add --host "$host_id" "${skill_args[@]}" >/dev/null 2>&1; then
    warn "$label: agent-add install failed; falling back to direct copy" >&2
    return 1
  fi

  echo "$(( ${#skill_args[@]} / 2 ))"
  return 0
}

# ── Kiro: native format ───────────────────────────────────────────────────────
# Steering → .kiro/steering/
# Skills   → .kiro/skills/<skill-name>/ (one folder per skill, per Agent Skills spec)
#            via agent-add when npx is available, else direct copy
_install_kiro() {
  local strut_home="$1"
  local project_root="$2"

  local skill_count=0
  skill_count=$(cd "$project_root" && _agent_add_install_skills "$strut_home" "kiro" "Kiro") || skill_count=""

  if [ -z "$skill_count" ]; then
    # Install skills — each skill folder goes directly under .kiro/skills/
    # per the Agent Skills spec (name must match parent directory name).
    local skills_target="$project_root/.kiro/skills"
    mkdir -p "$skills_target"

    skill_count=0
    for skill_dir in "$strut_home/.kiro/skills"/*/; do
      [ -d "$skill_dir" ] || continue
      local skill_name
      skill_name=$(basename "$skill_dir")
      [ -f "$skill_dir/SKILL.md" ] || continue

      # Remove existing copy if present
      if [ -d "$skills_target/$skill_name" ]; then
        rm -rf "${skills_target:?}/${skill_name:?}"
      fi
      cp -r "$skill_dir" "$skills_target/$skill_name"
      rm -f "$skills_target/$skill_name/.DS_Store" 2>/dev/null || true
      skill_count=$((skill_count + 1))
    done
  fi

  # Install steering
  local steering_count=0
  if [ -d "$strut_home/.kiro/steering" ]; then
    local steering_target="$project_root/.kiro/steering"
    mkdir -p "$steering_target"
    for f in "$strut_home/.kiro/steering"/*.md; do
      [ -f "$f" ] || continue
      local basename
      basename=$(basename "$f")
      # Prefix with strut- to avoid conflicts with user's own steering
      cp "$f" "$steering_target/strut-$basename"
      steering_count=$((steering_count + 1))
    done
  fi

  ok "Kiro: $skill_count skill(s) → .kiro/skills/ (Agent Skills spec)"
  ok "Kiro: $steering_count steering docs → .kiro/steering/strut-*.md"
}

# ── Claude Code: CLAUDE.md + .claude/skills/ ──────────────────────────────────
# Steering → CLAUDE.md (always loaded)
# Skills   → .claude/skills/<name>/ (Agent Skills spec — progressive disclosure)
#            via agent-add when npx is available, else direct copy
_install_claude() {
  local strut_home="$1"
  local project_root="$2"

  # Steering → CLAUDE.md (back up if hand-written)
  local claude_file="$project_root/CLAUDE.md"
  _backup_if_exists "$claude_file" "CLAUDE.md"
  _build_steering_content "$strut_home" > "$claude_file"
  ok "Claude: steering → CLAUDE.md"

  local skill_count=0
  skill_count=$(cd "$project_root" && _agent_add_install_skills "$strut_home" "claude-code" "Claude") || skill_count=""

  if [ -z "$skill_count" ]; then
    # Skills → .claude/skills/<name>/ (native Agent Skills support)
    local skills_target="$project_root/.claude/skills"
    mkdir -p "$skills_target"

    skill_count=0
    for skill_dir in "$strut_home/.kiro/skills"/*/; do
      [ -d "$skill_dir" ] || continue
      [ -f "$skill_dir/SKILL.md" ] || continue
      local name
      name=$(basename "$skill_dir")
      if [ -d "$skills_target/$name" ]; then
        rm -rf "${skills_target:?}/${name:?}"
      fi
      cp -r "$skill_dir" "$skills_target/$name"
      rm -f "$skills_target/$name/.DS_Store" 2>/dev/null || true
      skill_count=$((skill_count + 1))
    done
  fi

  ok "Claude: $skill_count skill → .claude/skills/ (Agent Skills spec)"
}

# ── Copilot: .github/copilot-instructions.md ──────────────────────────────────
# Steering → .github/copilot-instructions.md (always loaded)
# Skills   → .github/skills/<name>/ via agent-add (Agent Skills spec) when npx
#            is available; otherwise appended into the same file (Copilot has
#            no separate invocation mechanism to fall back on without it)
_install_copilot() {
  local strut_home="$1"
  local project_root="$2"

  local target="$project_root/.github/copilot-instructions.md"
  mkdir -p "$(dirname "$target")"

  local skill_count=""
  skill_count=$(cd "$project_root" && _agent_add_install_skills "$strut_home" "github-copilot" "Copilot") || skill_count=""

  if [ -n "$skill_count" ]; then
    _build_steering_content "$strut_home" > "$target"
    ok "Copilot: steering → .github/copilot-instructions.md"
    ok "Copilot: $skill_count skill(s) → .github/skills/ (Agent Skills spec)"
  else
    {
      _build_steering_content "$strut_home"
      echo ""
      echo "---"
      echo ""
      _build_skills_content "$strut_home"
    } > "$target"
    ok "Copilot: steering + skills → .github/copilot-instructions.md"
  fi
}

# ── Single rules file (Cursor, Windsurf, Zed, Cline, AGENTS.md) ──────────────
# Steering → top of file (always loaded)
# Skills   → via agent-add (Agent Skills spec) when an agent_add_host is given
#            and npx is available; otherwise appended below the steering
#            content in the same flat file (always available as reference).
#            agent_add_host is empty for zed/cline/agents — agent-add has no
#            host entry for them, so they always use the flat-file path.
_install_rules_file() {
  local strut_home="$1"
  local project_root="$2"
  local filename="$3"
  local tool_name="$4"
  local agent_add_host="${5:-}"

  local target="$project_root/$filename"
  _backup_if_exists "$target" "$filename"

  local skill_count=""
  if [ -n "$agent_add_host" ]; then
    skill_count=$(cd "$project_root" && _agent_add_install_skills "$strut_home" "$agent_add_host" "$tool_name") || skill_count=""
  fi

  if [ -n "$skill_count" ]; then
    _build_steering_content "$strut_home" > "$target"
    ok "$tool_name: steering → $filename"
    ok "$tool_name: $skill_count skill(s) → Agent Skills spec (via agent-add)"
  else
    {
      _build_steering_content "$strut_home"
      echo ""
      echo "---"
      echo ""
      _build_skills_content "$strut_home"
    } > "$target"
    ok "$tool_name: steering + skills → $filename"
  fi
}

# ── Generic: docs/ directory ──────────────────────────────────────────────────
# Steering → docs/strut-context.md
# Skills   → docs/strut-skills.md
_install_generic() {
  local strut_home="$1"
  local project_root="$2"

  mkdir -p "$project_root/docs"

  _build_steering_content "$strut_home" > "$project_root/docs/strut-context.md"
  ok "Generic: steering → docs/strut-context.md"

  {
    echo "# strut Operational Procedures"
    echo ""
    _build_skills_content "$strut_home"
  } > "$project_root/docs/strut-skills.md"
  ok "Generic: skills → docs/strut-skills.md"
}

# ── All formats ───────────────────────────────────────────────────────────────
_install_all() {
  local strut_home="$1"
  local project_root="$2"

  echo ""
  log "Installing all AI context formats..."
  echo ""

  _install_kiro "$strut_home" "$project_root"
  _install_claude "$strut_home" "$project_root"
  _install_rules_file "$strut_home" "$project_root" ".cursorrules" "Cursor" "cursor"
  _install_rules_file "$strut_home" "$project_root" ".windsurfrules" "Windsurf" "windsurf"
  _install_rules_file "$strut_home" "$project_root" ".rules" "Zed"
  _install_rules_file "$strut_home" "$project_root" ".clinerules" "Cline"
  _install_copilot "$strut_home" "$project_root"
  _install_rules_file "$strut_home" "$project_root" "AGENTS.md" "Generic agents"
  _install_generic "$strut_home" "$project_root"

  echo ""
  ok "All formats installed"
}

# ── List ──────────────────────────────────────────────────────────────────────
_skills_list() {
  local strut_home="${STRUT_HOME:-$CLI_ROOT}"
  local skills_dir="$strut_home/.kiro/skills"
  local steering_dir="$strut_home/.kiro/steering"

  echo ""
  echo -e "${BLUE}Steering (always-on context):${NC}"
  echo ""
  if [ -d "$steering_dir" ]; then
    for f in "$steering_dir"/*.md; do
      [ -f "$f" ] || continue
      local name
      name=$(basename "$f" .md)
      echo -e "  ${GREEN}✓${NC} $name"
    done
  else
    echo "  (none)"
  fi

  echo ""
  echo -e "${BLUE}Skills (on-demand procedures):${NC}"
  echo ""

  if [ ! -d "$skills_dir" ]; then
    echo "  (none)"
    return 0
  fi

  for skill_dir in "$skills_dir"/*/; do
    [ -d "$skill_dir" ] || continue
    local name
    name=$(basename "$skill_dir")
    local skill_file="$skill_dir/SKILL.md"
    if [ -f "$skill_file" ]; then
      local desc
      desc=$(sed -n '/^description:/s/^description: *//p' "$skill_file" | head -1)
      if [ -n "$desc" ]; then
        if [ ${#desc} -gt 65 ]; then
          desc="${desc:0:62}..."
        fi
        echo -e "  ${GREEN}✓${NC} $name"
        echo "    $desc"
      else
        echo -e "  ${GREEN}✓${NC} $name"
      fi

      # List reference files (progressive-disclosure detail)
      if [ -d "$skill_dir/references" ]; then
        local ref
        for ref in "$skill_dir/references"/*.md; do
          [ -f "$ref" ] || continue
          echo "      → references/$(basename "$ref")"
        done
      fi
    fi
  done
  echo ""
}

# ── Usage ─────────────────────────────────────────────────────────────────────
_skills_usage() {
  echo ""
  echo "Usage: strut skills <command> [options]"
  echo ""
  echo "Commands:"
  echo "  list                          List available steering docs and skills"
  echo "  install [--format <fmt>]      Install AI context for your editor/tool"
  echo ""
  echo "Formats:"
  echo "  kiro      Kiro IDE [default]"
  echo "              steering → .kiro/steering/strut-*.md"
  echo "              skills   → via agent-add (Agent Skills spec), falls back to .kiro/skills/"
  echo "  claude    Claude Code / Claude Desktop"
  echo "              steering → CLAUDE.md"
  echo "              skills   → via agent-add (Agent Skills spec), falls back to .claude/skills/"
  echo "  cursor    Cursor"
  echo "              steering → .cursorrules"
  echo "              skills   → via agent-add (Agent Skills spec), falls back to inline .cursorrules"
  echo "  windsurf  Windsurf"
  echo "              steering → .windsurfrules"
  echo "              skills   → via agent-add (Agent Skills spec), falls back to inline .windsurfrules"
  echo "  copilot   GitHub Copilot"
  echo "              steering → .github/copilot-instructions.md"
  echo "              skills   → via agent-add (Agent Skills spec), falls back to inline copilot-instructions.md"
  echo "  zed       Zed (also reads .cursorrules, CLAUDE.md)"
  echo "              steering + skills → .rules"
  echo "  cline     Cline"
  echo "              steering + skills → .clinerules"
  echo "  agents    Generic agent convention"
  echo "              steering + skills → AGENTS.md"
  echo "  generic   Any tool (separate files)"
  echo "              steering → docs/strut-context.md"
  echo "              skills   → docs/strut-skills.md"
  echo "  all       Generate all formats at once"
  echo ""
  echo "kiro/claude/cursor/windsurf/copilot install skills via agent-add"
  echo "(https://github.com/pea3nut/agent-add) when npx is available, so skills"
  echo "land as real Agent Skills — loaded on demand, not always inlined into"
  echo "context. zed/cline/agents/generic have no agent-add host and always get"
  echo "everything flattened into one file."
  echo ""
  echo "Examples:"
  echo "  strut skills list"
  echo "  strut skills install                        # Kiro (default)"
  echo "  strut skills install --format claude        # Claude Code"
  echo "  strut skills install --format cursor        # Cursor"
  echo "  strut skills install --format copilot       # GitHub Copilot"
  echo "  strut skills install --format all           # Everything"
  echo ""
}
