SERVICE_WEBSERVER_NAME=webserver
SERVICE_WEBSERVER_PORT=8000
SERVICE_WEBSERVER_HEALTH_PATH=/

SERVICE_POSTGRES_NAME=postgres
SERVICE_POSTGRES_PORT=5432
SERVICE_POSTGRES_DB=true

SERVICE_REDIS_NAME=redis
SERVICE_REDIS_PORT=6379
