SERVICE_WEB_NAME=web
SERVICE_WEB_PORT=3000
SERVICE_WEB_HEALTH_PATH=/api/health

SERVICE_POSTGRES_NAME=postgres
SERVICE_POSTGRES_PORT=5432
SERVICE_POSTGRES_DB=true

SERVICE_PROXY_NAME=proxy
SERVICE_PROXY_PORT=80
